get_users:
    path: /users
    controller: App\Controller\UserController::getAllUsers
    methods: [GET]

get_user:
    path: /users/{id}
    controller: App\Controller\UserController::getUserById
    methods: [GET]

create_user:
    path: /users
    controller: App\Controller\UserController::createUser
    methods: [POST]

update_user:
    path: /users/{id}
    controller: App\Controller\UserController::updateUser
    methods: [PUT]

delete_user:
    path: /users/{id}
    controller: App\Controller\UserController::deleteUser
    methods: [DELETE]

login:
    path: /login
    controller: App\Controller\UserController::login
    methods: [POST]
