get_users:
    path: /users
    controller: App\Controller\UserController::index
    methods: [GET]

get_user:
    path: /users/{id}
    controller: App\Controller\UserController::show
    methods: [GET]

create_user:
    path: /users
    controller: App\Controller\UserController::create
    methods: [POST]

update_user:
    path: /users/{id}
    controller: App\Controller\UserController::update
    methods: [PUT]

delete_user:
    path: /users/{id}
    controller: App\Controller\UserController::delete
    methods: [DELETE]

login:
    path: /login
    controller: App\Controller\UserController::login
    methods: [POST]
